In [ ]:
from data import get_data, exclude_columns
import matplotlib.pyplot as plt
import numpy as np


In [4]:
df, X = get_data()
print(df.keys())
df["stab_conc_uM"].unique()

Index(['Filename', 'Channel', 'Flags', 'Connectivity', 'Maximum Island Area',
       'Maximum Void Area', 'Island Area Change', 'Void Area Change',
       'Initial Maximum Island Area', 'Initial 2nd Maximum Island Area',
       'Maximum Kurtosis', 'Maximum Median Skewness', 'Maximum Mode Skewness',
       'Kurtosis Change', 'Median Skewness Change', 'Mode Skewness Change',
       'Mean Speed', 'Speed Change', 'Mean Flow Direction',
       'Flow Directional Spread', 'stab_conc_uM', 'stab_name', 'mt_conc_uM',
       'actin_conc_uM', 'channel', 'trial', 'time_PT', 'spatial_x',
       'spatial_y'],
      dtype='object')


array([5.0e+00, 5.0e-01, 1.0e+00, 2.5e+03, 2.5e+00, 5.0e+02, 1.0e+03,
       2.0e+03])

In [10]:
print(df["stab_conc_uM"].unique())
print(df["stab_name"].unique())
print(df["mt_conc_uM"].unique())
print(df["actin_conc_uM"].unique())
print(df["time_PT"].unique())

[5.0e+00 5.0e-01 1.0e+00 2.5e+03 2.5e+00 5.0e+02 1.0e+03 2.0e+03]
['TX' 'GMP']
[3.19]
[2.62]
[6 1 2 3 4 5]


In [11]:
df.to_csv("data.csv", index=False)